MEMORY {
	FLASH (rx): ORIGIN = 0x08000000, LENGTH = 64K
	RAM (rxw):  ORIGIN = 0x20000000, LENGTH = 20k
}

SECTIONS {
	. = ORIGIN(FLASH);
	.text : {
		*(.vectors)
		*(.text*)
		*(.rodata*)
	} > FLASH

	_sidata = LOADADDR(.data);
	.data : {
		_sdata = .;
		*(.data*)
		_edata = .;
	} > RAM AT > FLASH

	.bss : {
		_sbss = .;
		*(.bss*)
		*(COMMON)
		_ebss = .;
	} > RAM

	_estack = ORIGIN(RAM) + LENGTH(RAM);
}
